[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "spirosim"
version = "0.2.0"

[project.scripts]
analysis = "spiro_analysis.cli:analysis"

[tool.setuptools.packages.find]
where = ["src"]