[experiment]
name = "PheromoneExperiment_Trial1_Before_20260121"
description = ""
date = "2026-01-21"

[paths]
data_dir = "results/PheromoneExperiment_Trial1_Before_20260121"
output_dir = "results/PheromoneExperiment_Trial1_Before_20260121"

[preprocess]

[analysis]
input_dir = "results/PheromoneExperiment_Trial1_Before_20260121/cropped_background_subtracted"
output_dir = "results/PheromoneExperiment_Trial1_Before_20260121" 
do_napari = true

[analysis.tp_batch]
brightness_threshold = 4
minimum_mass_threshold = 5000
diameter_threshold = 51 # must be odd
save_batch_frames = false

[analysis.labels_stack]
radius = 6
brightness_col = "mass"
min_brightness = 200
save_napari_edits = true

[analysis.track]
search_range = 150
memory = 10
save_tracks_df = true
