[experiment]
name = "PheromoneExperiment_Trial1_After_20260121"
description = ""
date = "2026-01-21"

[paths]
data_dir = "data/PheromoneExperiment_Trial1_After_20260121"
output_dir = "results/PheromoneExperiment_Trial1_After_20260121"

[preprocess]
input_dir = "data/PheromoneExperiment_Trial1_After_20260121" 
output_dir = "results/PheromoneExperiment_Trial1_After_20260121/preprocessed" 
do_merge = false
save_background = true
save_background_subtracted = true
save_cropped_frames = true


[analysis]
input_dir = "results/PheromoneExperiment_Trial1_After_20260121/preprocessed/cropped"
output_dir = "results/PheromoneExperiment_Trial1_After_20260121" 
do_napari = true
features_path = "results/PheromoneExperiment_Trial1_After_20260121/edited_features_batch.csv"

[analysis.tp_batch]
brightness_threshold = 4
minimum_mass_threshold = 5000
diameter_threshold = 51 # must be odd
save_batch_frames = false

[analysis.labels_stack]
radius = 6
brightness_col = "mass"
min_brightness = 200
save_napari_edits = true

[analysis.track]
search_range = 120
memory = 5
remove_stubs = true
stubs_threshold = 5
save_tracks_df = true
